{% set name = "climpred" %}
{% set version = "2.1.0.post1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0a7038664d16c53a2d0951a2027230cd1ff97a94a96d8571705f9cfc4c577360

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >3.5
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >3.5
    - eofs
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - scipy
    - tqdm
    - xarray >=0.14.1
    - xrft
    - xskillscore >=0.0.12

test:
  imports:
    - climpred

about:
  home: http://github.com/bradyrx/climpred
  license: MIT
  license_file: LICENSE.txt
  summary: an xarray wrapper for analysis of ensemble forecast models for climate prediction
  doc_url: http://climpred.readthedocs.io/
  dev_url: https://github.com/bradyrx/climpred

extra:
  recipe-maintainers:
    - bradyrx
