travis:
  secure:
    BINSTAR_TOKEN: enYmibjBWkeEjIm5okD6QIW7okTlUhSdqvXMNbnAdjdhQkHFAVx68kzgazv2fgmBxkB8IDECWUjo9sdQagvPfhSmyVe4JGwFbGCdOV2KjxSz840B+GWM+7tfF7oSL/RHpwaynCW/71KXc0X4sbr4tqOb0iDhhFVospuRgYZkx8m35/u9Gi+xNpx0upKtkNUlnB7LCo89ROUxMFDSt/t1Av8XTr7UHaEW0MtyrHNHsplsheXlR/9lKWPwRYr2nkj0uxRzDf5h2r1cifk7UuWG5NN6gvCEvnIntgmCquPqmnx8kaax+Q8ch6NntOMrGc+oOsFE7qxI7RKNMfsZSF+5jmX6xIkxmV5vagGjBSJf7Ii34/UAD3ZA3gBYPcTVeuSaKsDZyelO832D2RGRX7/UB0Hqkkh+pkI5lrhGr9qds5NkDFj3HG5qMFro85UVjhs1B9Oa5unTX3xYRSZ6d//zh+tCQJkNQG6PhzHQmO6kAp3upyBJ8MXrOqmIIwhH+bjwcnFyrpD5IloSAlNhF1aTeA0XnCLvBPNZZcpHXddy1mkpWB+cCzktMVJzy9V9FFchrkITiVZY7Mnw511Lkiy5vhJneC86dthOuSsnsVFTtOGgRzmMRPS9Hgqc4ff/Psmb3gtNk/oxrm5/1N244HkWLnnskjG8YCj12+ja9nNJtN4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
